export const GET_WEATHER = {
  PENDING: "GET_WEATHER_PENDING",
  SUCCESS: "GET_WEATHER_SUCCESS",
  REJECTED: "GET_WEATHER_REJECTED",
  FORECASTSUCCESS: "GET_FORECAST_SUCCESS",
  HOURLYSUCCESS: "GET_HOURLY_SUCCESS"
};
